version: '3.0'
services:
  dbPostgres:
    image: postgres:10
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pix

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


